---
title: 'Workflow: code style'
author: "Gabriel Montes"
date: "2025-07-17"
output: pdf_document
---

### 1. Restyle the following pipelines following the guidelines above.

```{r}
library(tidyverse)
library(dplyr)
library(nycflights13)
flights|>filter(dest=="IAH")|>group_by(year,month,day)|>summarize(n=n(),
delay=mean(arr_delay,na.rm=TRUE))|>filter(n>10)

flights|>filter(carrier=="UA",dest%in%c("IAH","HOU"),sched_dep_time>
0900,sched_arr_time<2000)|>group_by(flight)|>summarize(delay=mean(
arr_delay,na.rm=TRUE),cancelled=sum(is.na(arr_delay)),n=n())|>filter(n>10)
```

restyled

```{r}
houston_daily_summary <- flights |> 
  filter(dest == "IAH") |> 
  group_by(year, month, day) |> 
  summarize(
    n     = n(),
    delay = mean(arr_delay, na.rm = TRUE)
  ) |> 
  filter(n > 10)
```

```{r}
ua_daytime_summary <- flights |> 
  filter(
    carrier == "UA", 
    dest %in% c("IAH", "HOU"), 
    sched_dep_time >  0900, 
    sched_arr_time < 2000
  ) |> 
  group_by(flight) |> 
  summarize(
    delay     = mean(arr_delay, na.rm = TRUE),
    cancelled = sum(is.na(arr_delay)),
    n         = n()
  ) |> 
  filter(n > 10)

```